[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "crafting-cli"
version = "0.1.2"
description = "Terminal tabanlı not kasası"
readme = "README.md"
requires-python =">=3.10"
dependencies = [
    "typer>= 0.9.0",
    "rich>=13.0.0",
    "cryptography>=41.0.0",
]

[project.scripts]
cr = "crafting.cli.main_cli:app"
crafting = "crafting.cli.main_cli:app"
